import io
import logging
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

logger = logging.getLogger("meetingmate.pdf_generator")

class PDFGenerator:
    def __init__(self):
        pass

    def create_pdf_report(self, analysis_data: Dict[str, Any], transcript: List[Dict[str, str]] = None) -> bytes:
        """
        Generates an executive PDF report using reportlab.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()

        # Custom Palette: Slate Navy & Indigo
        PRIMARY_COLOR = colors.HexColor("#6366f1")
        SECONDARY_COLOR = colors.HexColor("#06b6d4")
        DARK_TEXT = colors.HexColor("#0f172a")
        LIGHT_BG = colors.HexColor("#f8fafc")
        BORDER_COLOR = colors.HexColor("#e2e8f0")

        # Custom Paragraph Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=PRIMARY_COLOR,
            spaceAfter=4
        )

        meta_style = ParagraphStyle(
            'ReportMeta',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=12
        )

        h2_style = ParagraphStyle(
            'ReportH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=PRIMARY_COLOR,
            spaceBefore=12,
            spaceAfter=6
        )

        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=DARK_TEXT
        )

        bullet_style = ParagraphStyle(
            'ReportBullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=DARK_TEXT,
            leftIndent=15,
            spaceBefore=3
        )

        table_header_style = ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            textColor=colors.white
        )

        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            textColor=DARK_TEXT
        )

        story = []

        # Header Title
        title = analysis_data.get("title", "Meeting Overview & Key Takeaways")
        story.append(Paragraph(f"<b>{title}</b>", title_style))

        # Metadata Subtitle
        date_str = analysis_data.get("date", "2026-08-16")
        duration = analysis_data.get("duration", "N/A")
        participants = ", ".join(analysis_data.get("participants", []))
        
        meta_text = f"<b>Generated by MeetingMate GenAI</b> | Date: {date_str} | Duration: {duration}<br/><b>Participants:</b> {participants}"
        story.append(Paragraph(meta_text, meta_style))

        story.append(HRFlowable(width="100%", thickness=1, color=BORDER_COLOR, spaceBefore=4, spaceAfter=12))

        # Executive Summary Section
        story.append(Paragraph("Executive Summary", h2_style))
        summary_text = analysis_data.get("executive_summary", "")
        story.append(Paragraph(summary_text, body_style))
        story.append(Spacer(1, 10))

        # Key Decisions Section
        story.append(Paragraph("Key Decisions Agreed", h2_style))
        for dec in analysis_data.get("key_decisions", []):
            story.append(Paragraph(f"• {dec}", bullet_style))
        story.append(Spacer(1, 12))

        # Action Items Section
        story.append(Paragraph("Action Items & Accountabilities Matrix", h2_style))
        
        action_items = analysis_data.get("action_items", [])
        table_data = [
            [
                Paragraph("<b>Task / Action Item</b>", table_header_style),
                Paragraph("<b>Assignee</b>", table_header_style),
                Paragraph("<b>Priority</b>", table_header_style),
                Paragraph("<b>Deadline</b>", table_header_style)
            ]
        ]

        for item in action_items:
            table_data.append([
                Paragraph(item.get("task", ""), table_cell_style),
                Paragraph(item.get("assignee", "Unassigned"), table_cell_style),
                Paragraph(f"<b>{item.get('priority', 'Medium')}</b>", table_cell_style),
                Paragraph(item.get("deadline", "TBD"), table_cell_style)
            ])

        t = Table(table_data, colWidths=[240, 110, 80, 110])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [LIGHT_BG, colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 14))

        # Main Topics
        topics = analysis_data.get("topics", [])
        if topics:
            story.append(Paragraph("Main Discussion Topics", h2_style))
            for top in topics:
                story.append(Paragraph(f"<b>{top.get('name')}:</b> {top.get('summary')}", bullet_style))
            story.append(Spacer(1, 14))

        # Build PDF Document
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
