import os
import io
import logging
from typing import Dict, Any
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE

logger = logging.getLogger("meetingmate.ppt_generator")

# Color Palette: Deep Navy & Electric Violet/Teal accents
NAVY = RGBColor(15, 23, 42)        # #0f172a
DARK_BLUE = RGBColor(30, 41, 59)   # #1e293b
PURPLE_ACCENT = RGBColor(124, 58, 237) # #7c3aed
CYAN_ACCENT = RGBColor(14, 165, 233)   # #0ea5e9
WHITE = RGBColor(255, 255, 255)
LIGHT_GRAY = RGBColor(241, 245, 249)
DARK_TEXT = RGBColor(51, 65, 85)

class PPTGenerator:
    def __init__(self):
        pass

    def create_presentation(self, analysis_data: Dict[str, Any], output_path: str = None) -> bytes:
        """
        Creates a PowerPoint presentation using python-pptx based on structured meeting analysis.
        """
        prs = Presentation()
        # Set 16:9 widescreen dimensions
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)
        blank_slide_layout = prs.slide_layouts[6]

        # ----------------------------------------------------
        # SLIDE 1: Title Slide (Dark Theme)
        # ----------------------------------------------------
        slide1 = prs.slides.add_slide(blank_slide_layout)
        
        # Background rect
        bg1 = slide1.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, Inches(13.333), Inches(7.5))
        bg1.fill.solid()
        bg1.fill.fore_color.rgb = NAVY
        bg1.line.fill.background()

        # Accent bar
        accent1 = slide1.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(1), Inches(1.5), Inches(0.15), Inches(4.5))
        accent1.fill.solid()
        accent1.fill.fore_color.rgb = PURPLE_ACCENT
        accent1.line.fill.background()

        # Title Box
        title_box = slide1.shapes.add_textbox(Inches(1.4), Inches(1.8), Inches(10.5), Inches(2.0))
        tf1 = title_box.text_frame
        tf1.word_wrap = True
        p1 = tf1.paragraphs[0]
        p1.text = analysis_data.get("title", "Meeting Overview & Key Takeaways")
        p1.font.size = Pt(36)
        p1.font.bold = True
        p1.font.color.rgb = WHITE
        p1.font.name = "Arial"

        # Subtitle Box
        sub_box = slide1.shapes.add_textbox(Inches(1.4), Inches(3.8), Inches(10.5), Inches(1.5))
        tf_sub = sub_box.text_frame
        tf_sub.word_wrap = True
        p_sub = tf_sub.paragraphs[0]
        date_str = analysis_data.get("date", "2026-08-16")
        duration = analysis_data.get("duration", "N/A")
        participants = ", ".join(analysis_data.get("participants", []))
        
        p_sub.text = f"Generated by MeetingMate GenAI  |  Date: {date_str}  |  Duration: {duration}\nParticipants: {participants}"
        p_sub.font.size = Pt(16)
        p_sub.font.color.rgb = CYAN_ACCENT
        p_sub.font.name = "Arial"

        # ----------------------------------------------------
        # SLIDE 2: Executive Summary & Key Decisions
        # ----------------------------------------------------
        slide2 = prs.slides.add_slide(blank_slide_layout)
        
        # Title
        tbox2 = slide2.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.7), Inches(1.0))
        tf2 = tbox2.text_frame
        p2 = tf2.paragraphs[0]
        p2.text = "Executive Summary & Key Decisions"
        p2.font.size = Pt(28)
        p2.font.bold = True
        p2.font.color.rgb = NAVY

        # Exec Summary Card (Left)
        card1 = slide2.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.8), Inches(1.6), Inches(5.6), Inches(5.2))
        card1.fill.solid()
        card1.fill.fore_color.rgb = LIGHT_GRAY
        card1.line.color.rgb = PURPLE_ACCENT
        
        tf_c1 = card1.text_frame
        tf_c1.word_wrap = True
        p_c1_title = tf_c1.paragraphs[0]
        p_c1_title.text = "Executive Summary"
        p_c1_title.font.size = Pt(20)
        p_c1_title.font.bold = True
        p_c1_title.font.color.rgb = PURPLE_ACCENT
        
        p_c1_body = tf_c1.add_paragraph()
        p_c1_body.text = "\n" + analysis_data.get("executive_summary", "")
        p_c1_body.font.size = Pt(14)
        p_c1_body.font.color.rgb = DARK_TEXT

        # Key Decisions Card (Right)
        card2 = slide2.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(6.8), Inches(1.6), Inches(5.6), Inches(5.2))
        card2.fill.solid()
        card2.fill.fore_color.rgb = LIGHT_GRAY
        card2.line.color.rgb = CYAN_ACCENT

        tf_c2 = card2.text_frame
        tf_c2.word_wrap = True
        p_c2_title = tf_c2.paragraphs[0]
        p_c2_title.text = "Key Decisions Agreed"
        p_c2_title.font.size = Pt(20)
        p_c2_title.font.bold = True
        p_c2_title.font.color.rgb = CYAN_ACCENT

        for decision in analysis_data.get("key_decisions", []):
            p_dec = tf_c2.add_paragraph()
            p_dec.text = f"• {decision}"
            p_dec.font.size = Pt(13)
            p_dec.font.color.rgb = DARK_TEXT
            p_dec.space_before = Pt(8)

        # ----------------------------------------------------
        # SLIDE 3: Action Items & Responsibilities (Table)
        # ----------------------------------------------------
        slide3 = prs.slides.add_slide(blank_slide_layout)
        
        tbox3 = slide3.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.7), Inches(1.0))
        tf3 = tbox3.text_frame
        p3 = tf3.paragraphs[0]
        p3.text = "Action Items & Accountabilities"
        p3.font.size = Pt(28)
        p3.font.bold = True
        p3.font.color.rgb = NAVY

        action_items = analysis_data.get("action_items", [])
        rows = len(action_items) + 1
        cols = 4

        table_shape = slide3.shapes.add_table(rows, cols, Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))
        table = table_shape.table
        table.columns[0].width = Inches(5.5)  # Task
        table.columns[1].width = Inches(2.2)  # Assignee
        table.columns[2].width = Inches(1.8)  # Priority
        table.columns[3].width = Inches(2.2)  # Deadline

        # Header Row Styling
        headers = ["Action Item / Task", "Assignee", "Priority", "Target Deadline"]
        for c_idx, h_text in enumerate(headers):
            cell = table.cell(0, c_idx)
            cell.fill.solid()
            cell.fill.fore_color.rgb = DARK_BLUE
            p = cell.text_frame.paragraphs[0]
            p.text = h_text
            p.font.size = Pt(14)
            p.font.bold = True
            p.font.color.rgb = WHITE
            p.alignment = PP_ALIGN.LEFT

        # Data Rows Styling
        for r_idx, item in enumerate(action_items, start=1):
            row_vals = [
                item.get("task", ""),
                item.get("assignee", "Unassigned"),
                item.get("priority", "Medium"),
                item.get("deadline", "TBD")
            ]
            for c_idx, val in enumerate(row_vals):
                cell = table.cell(r_idx, c_idx)
                cell.fill.solid()
                cell.fill.fore_color.rgb = LIGHT_GRAY if r_idx % 2 == 1 else WHITE
                p = cell.text_frame.paragraphs[0]
                p.text = val
                p.font.size = Pt(13)
                p.font.color.rgb = DARK_TEXT

        # Save presentation stream
        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        
        if output_path:
            with open(output_path, "wb") as f:
                f.write(buffer.getvalue())

        return buffer.getvalue()
